quarkus.log.level=ALL
quarkus.log.category."io.quarkus.resteasy".level=DEBUG
quarkus.http.access-log.enabled=true
quarkus.log.category."org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider".level=TRACE
quarkus.log.category."org.jboss.resteasy.plugins.providers.jackson".level=TRACE


#server.port=8081
#quarkus.resteasy.json.enabled=true

#POSTGRESQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=secretpassword
quarkus.datasource.devservices.port=53933
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:53933/quarkus

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Enable CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H

#KEYCLOAK
quarkus.oidc.client-id=quarkus-backend
quarkus.oidc.credentials.secret=MPPC8UVOnlshs2zjkq5qqVksNawhw0Ik
quarkus.oidc.tls.verification=none
quarkus.oidc.client.port=8181
quarkus.oidc.auth-server-url=http://localhost:8181/realms/dmn_tool

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enabled=true