#server.port=8081

#quarkus.resteasy.json.enabled=true

# configure your datasource
quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=notification
#quarkus.datasource.password=secret
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/notifications

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

