quarkus.datasource.username=postgres
quarkus.datasource.password=postgrespassword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/dmn-studio

quarkus.rest.client.keycloak-api.url=http://localhost:8181
quarkus.rest.client.keycloak-api.realm=dmn_studio
quarkus.oidc.client-id=quarkus-backend
quarkus.oidc.credentials.secret=YsVBOJj2avKCn7erFaNKaWdMmGXbjGgY
quarkus.oidc.auth-server-url=http://localhost:8181/realms/dmn_studio
quarkus.oidc.authentication.user-info-required=false

#quarkus.rest-client.operaton_rest_api_json.url=http://localhost:8085
quarkus.rest-client.operaton_rest_api_test.url=http://localhost:8085
quarkus.rest-client.operaton_rest_api_ut.url=http://localhost:8085
quarkus.rest-client.operaton_rest_api_acc.url=http://localhost:8085
quarkus.rest-client.operaton_rest_api_prod.url=http://localhost:8085

quarkus.openapi-generator.operaton-rest-api_json.auth.basic_auth.username=demo
quarkus.openapi-generator.operaton-rest-api_json.auth.basic_auth.password=demo

quarkus.rest-client.keycloak-api.url=http://localhost:8181
quarkus.http.root-path=/api