quarkus.http.access-log.enabled=true

#POSTGRESQL
quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=
#quarkus.datasource.password=
#quarkus.datasource.jdbc.url=
quarkus.hibernate-orm.schema-management.strategy=update

# Enable CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H

#KEYCLOAK
#quarkus.oidc.client-id=
#quarkus.oidc.credentials.secret=
#quarkus.oidc.auth-server-url=

# REST Client URLs
#quarkus.rest-client.keycloak-api.url=

# Security Permissions
quarkus.http.auth.permission.public.paths=/*
quarkus.http.auth.permission.public.policy=permit
quarkus.keycloak.policy-enforcer.enabled=false

# Operaton REST client
quarkus.openapi-generator.codegen.generate-part-filename=false
quarkus.openapi-generator.codegen.input-base-dir=src/main/resources/openapi


# Container Image Configuration
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=SynTouchNL
quarkus.container-image.name=dmn-studio-backend
quarkus.container-image.tag=latest
quarkus.container-image.build=true
quarkus.container-image.push=false

# Multi-platform support for Jib
quarkus.jib.platforms=linux/amd64,linux/arm64
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.23

