CREATE SEQUENCE IF NOT EXISTS change_log_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS dmns_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS domains_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS environments_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE change_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approved     BOOLEAN,
    assigned_to  VARCHAR(255),
    description  VARCHAR(255)                            NOT NULL,
    timestamp    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    submitted_by VARCHAR(255)                            NOT NULL,
    dmn_id       BIGINT,
    version      BIGINT,
    CONSTRAINT change_log_pkey PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment   VARCHAR(255),
    commenter VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    change_id BIGINT,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE deployments
(
    id             BIGINT                      NOT NULL,
    deployed_by    VARCHAR(255)                NOT NULL,
    deployed_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deployment_ref VARCHAR(255)                NOT NULL,
    dmn_id         BIGINT                      NOT NULL,
    dmn_version    BIGINT                      NOT NULL,
    environment_id BIGINT                      NOT NULL,
    CONSTRAINT deployments_pkey PRIMARY KEY (id, dmn_id, dmn_version)
);

CREATE TABLE dmns
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(45)                             NOT NULL,
    owner     VARCHAR(45)                             NOT NULL,
    domain_id BIGINT                                  NOT NULL,
    CONSTRAINT dmns_pkey PRIMARY KEY (id)
);

CREATE TABLE domains
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(45)                             NOT NULL,
    CONSTRAINT domains_pkey PRIMARY KEY (id)
);

CREATE TABLE environments
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT environments_pkey PRIMARY KEY (id)
);

CREATE TABLE key_value_pairs
(
    key               VARCHAR(255),
    type              VARCHAR(255),
    value             VARCHAR(255),
    test_decisionname VARCHAR(255) NOT NULL,
    CONSTRAINT key_value_pairs_pkey PRIMARY KEY (test_decisionname)
);

CREATE TABLE unittests
(
    decisionname VARCHAR(255) NOT NULL,
    passed       BOOLEAN,
    title        VARCHAR(255),
    dmn_id       BIGINT,
    version      BIGINT,
    CONSTRAINT unittests_pkey PRIMARY KEY (decisionname)
);

CREATE TABLE versions
(
    dmn_id        BIGINT                      NOT NULL,
    version       BIGINT                      NOT NULL,
    created_by    VARCHAR(255)                NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    file_blob     BYTEA                       NOT NULL,
    modified_by   VARCHAR(255),
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    status        INTEGER                     NOT NULL,
    CONSTRAINT versions_pkey PRIMARY KEY (dmn_id, version)
);

ALTER TABLE change_log
    ADD CONSTRAINT fk1jh1vns1kri276ilw26qibal3 FOREIGN KEY (dmn_id, version) REFERENCES versions (dmn_id, version) ON DELETE NO ACTION;

ALTER TABLE deployments
    ADD CONSTRAINT fker8ts9lt9w4ob78rf6dguvn11 FOREIGN KEY (dmn_id, dmn_version) REFERENCES versions (dmn_id, version) ON DELETE NO ACTION;

ALTER TABLE comments
    ADD CONSTRAINT fkfa6b82s9nf5fd6cnxcv0j0uo6 FOREIGN KEY (change_id) REFERENCES change_log (id) ON DELETE NO ACTION;

ALTER TABLE versions
    ADD CONSTRAINT fkicuhxy535xa2pbx4k5io5lwhv FOREIGN KEY (dmn_id) REFERENCES dmns (id) ON DELETE NO ACTION;

ALTER TABLE deployments
    ADD CONSTRAINT fkl9wdtf8kr7ijmjwr4dge5lm10 FOREIGN KEY (environment_id) REFERENCES environments (id) ON DELETE NO ACTION;

ALTER TABLE key_value_pairs
    ADD CONSTRAINT fkmujqk852lsxej3q4403n8ssdl FOREIGN KEY (test_decisionname) REFERENCES unittests (decisionname) ON DELETE NO ACTION;

ALTER TABLE unittests
    ADD CONSTRAINT fkqis98owmy4sakoibp7readscc FOREIGN KEY (dmn_id, version) REFERENCES versions (dmn_id, version) ON DELETE NO ACTION;

ALTER TABLE dmns
    ADD CONSTRAINT fkrmumdbyxe4tnmywhf3lic2xus FOREIGN KEY (domain_id) REFERENCES domains (id) ON DELETE NO ACTION;