CREATE TABLE domains
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(45)                             NOT NULL,
    CONSTRAINT pk_domains PRIMARY KEY (id)
);

CREATE TABLE environments
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_environments PRIMARY KEY (id)
);

CREATE TABLE dmns
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(45)                             NOT NULL,
    owner     VARCHAR(45)                             NOT NULL,
    domain_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_dmns PRIMARY KEY (id),
    CONSTRAINT fk_dmns_domain FOREIGN KEY (domain_id) REFERENCES domains (id)
);

CREATE TABLE versions
(
    dmn_id        BIGINT                   NOT NULL,
    version       BIGINT                   NOT NULL,
    status        BIGINT                   NOT NULL,
    file_blob     BYTEA                    NOT NULL,
    modified_by   VARCHAR(255),
    modified_date TIMESTAMP WITH TIME ZONE,
    created_by    VARCHAR(255)             NOT NULL,
    created_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_versions PRIMARY KEY (dmn_id, version),
    CONSTRAINT fk_versions_dmn FOREIGN KEY (dmn_id) REFERENCES dmns (id)
);

CREATE TABLE change_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dmn_id       BIGINT,
    version      BIGINT,
    description  VARCHAR(255)                            NOT NULL,
    submitted_by VARCHAR(255)                            NOT NULL,
    assigned_to  VARCHAR(255),
    approved     BOOLEAN                                 NOT NULL,
    timestamp    TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_change_log PRIMARY KEY (id),
    CONSTRAINT fk_change_log_version FOREIGN KEY (dmn_id, version)
        REFERENCES versions (dmn_id, version)
);

CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    change_id BIGINT,
    commenter VARCHAR(255),
    comment   VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_change FOREIGN KEY (change_id) REFERENCES change_log (id)
);

CREATE TABLE deployments
(
    id             BIGINT                   NOT NULL,
    dmn_id         BIGINT                   NOT NULL,
    dmn_version    BIGINT                   NOT NULL,
    environment_id BIGINT                   NOT NULL,
    deployed_by    VARCHAR(255)             NOT NULL,
    deployed_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    deployment_ref VARCHAR(255)             NOT NULL,
    CONSTRAINT pk_deployments PRIMARY KEY (id, dmn_id, dmn_version),
    CONSTRAINT fk_deployments_version FOREIGN KEY (dmn_id, dmn_version)
        REFERENCES versions (dmn_id, version),
    CONSTRAINT fk_deployments_environment FOREIGN KEY (environment_id) REFERENCES environments (id)
);

CREATE TABLE unittests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    decision_name VARCHAR(255)                            NOT NULL,
    title         VARCHAR(256)                            NOT NULL,
    dmn_id        BIGINT,
    version       BIGINT,
    passed        BOOLEAN,
    CONSTRAINT pk_unittests PRIMARY KEY (id),
    CONSTRAINT fk_unittests_version FOREIGN KEY (dmn_id, version)
        REFERENCES versions (dmn_id, version)
);

CREATE TABLE key_value_pairs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    test_id    BIGINT,
    is_input   BOOLEAN,
    key_name   VARCHAR(255),
    value_text VARCHAR(255),
    value_type VARCHAR(255),
    CONSTRAINT pk_key_value_pairs PRIMARY KEY (id),
    CONSTRAINT fk_key_value_pairs_test FOREIGN KEY (test_id) REFERENCES unittests (id)
);

INSERT INTO domains (id, name)
VALUES (1, 'Bestuur'),
       (2, 'Sociaal domein'),
       (3, 'Fysieke leefomgeving'),
       (4, 'Publieksdiensten'),
       (5, 'Openbare order en veiligheid'),
       (6, 'Niet domeingebonden'),
       (7, 'Ondersteuning');

SELECT setval(pg_get_serial_sequence('domains', 'id'), (SELECT MAX(id) FROM domains), true);

INSERT INTO environments (id, name)
VALUES (1, 'Ontwikkel'),
       (2, 'Productie');

SELECT setval(pg_get_serial_sequence('environments', 'id'), (SELECT MAX(id) FROM environments), true);
