-- Existing installations were managed by Hibernate and have no Flyway history.
-- Flyway baselines those databases at V1, then this migration brings both the
-- legacy bootstrap schema and Hibernate-created schemas to the V1 entity model.

DO $$
DECLARE
    required_table TEXT;
BEGIN
    FOREACH required_table IN ARRAY ARRAY[
        'domains', 'environments', 'dmns', 'versions', 'change_log',
        'comments', 'deployments', 'unittests', 'key_value_pairs'
    ]
    LOOP
        IF to_regclass('public.' || required_table) IS NULL THEN
            RAISE EXCEPTION 'Cannot adopt existing schema: required table % is missing', required_table;
        END IF;
    END LOOP;
END $$;

ALTER TABLE unittests
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS decision_name VARCHAR(255);

ALTER TABLE key_value_pairs
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS test_id BIGINT,
    ADD COLUMN IF NOT EXISTS is_input BOOLEAN,
    ADD COLUMN IF NOT EXISTS key_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS value_text VARCHAR(255),
    ADD COLUMN IF NOT EXISTS value_type VARCHAR(255);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'unittests' AND column_name = 'decisionname'
    ) THEN
        EXECUTE 'UPDATE unittests SET decision_name = decisionname WHERE decision_name IS NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'key_value_pairs' AND column_name = 'key'
    ) THEN
        EXECUTE 'UPDATE key_value_pairs SET key_name = "key" WHERE key_name IS NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'key_value_pairs' AND column_name = 'value'
    ) THEN
        EXECUTE 'UPDATE key_value_pairs SET value_text = value WHERE value_text IS NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'key_value_pairs' AND column_name = 'type'
    ) THEN
        EXECUTE 'UPDATE key_value_pairs SET value_type = type WHERE value_type IS NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'key_value_pairs' AND column_name = 'test_decisionname'
    ) THEN
        EXECUTE '
            UPDATE key_value_pairs kv
            SET test_id = test.id
            FROM unittests test
            WHERE kv.test_id IS NULL
              AND kv.test_decisionname = test.decision_name';
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM unittests WHERE decision_name IS NULL) THEN
        RAISE EXCEPTION 'Cannot adopt existing schema: unittests contains rows without a decision name';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM key_value_pairs
        WHERE test_id IS NULL
    ) AND EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'key_value_pairs' AND column_name = 'test_decisionname'
    ) THEN
        RAISE EXCEPTION 'Cannot adopt existing schema: some key/value rows could not be matched to a unit test';
    END IF;
END $$;

-- Required for legacy schemas where these columns were nullable. IntelliJ warning can be ignored.
UPDATE unittests
SET title = decision_name
WHERE title IS NULL;

UPDATE change_log
SET approved = FALSE
WHERE approved IS NULL;

ALTER TABLE versions
    ALTER COLUMN status TYPE BIGINT USING status::BIGINT;

ALTER TABLE unittests
    ALTER COLUMN title TYPE VARCHAR(256),
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN decision_name SET NOT NULL,
    ALTER COLUMN title SET NOT NULL;

ALTER TABLE key_value_pairs
    ALTER COLUMN id SET NOT NULL;

ALTER TABLE change_log
    ALTER COLUMN approved SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'change_log'
          AND column_name = 'timestamp' AND data_type = 'timestamp without time zone'
    ) THEN
        EXECUTE 'ALTER TABLE change_log ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE USING timestamp AT TIME ZONE ''UTC''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'comments'
          AND column_name = 'timestamp' AND data_type = 'timestamp without time zone'
    ) THEN
        EXECUTE 'ALTER TABLE comments ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE USING timestamp AT TIME ZONE ''UTC''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'deployments'
          AND column_name = 'deployed_date' AND data_type = 'timestamp without time zone'
    ) THEN
        EXECUTE 'ALTER TABLE deployments ALTER COLUMN deployed_date TYPE TIMESTAMP WITH TIME ZONE USING deployed_date AT TIME ZONE ''UTC''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'versions'
          AND column_name = 'modified_date' AND data_type = 'timestamp without time zone'
    ) THEN
        EXECUTE 'ALTER TABLE versions ALTER COLUMN modified_date TYPE TIMESTAMP WITH TIME ZONE USING modified_date AT TIME ZONE ''UTC''';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'versions'
          AND column_name = 'created_date' AND data_type = 'timestamp without time zone'
    ) THEN
        EXECUTE 'ALTER TABLE versions ALTER COLUMN created_date TYPE TIMESTAMP WITH TIME ZONE USING created_date AT TIME ZONE ''UTC''';
    END IF;
END $$;

-- Remove the legacy relationship before replacing the old text primary keys.
DO $$
DECLARE
    constraint_to_drop RECORD;
BEGIN
    FOR constraint_to_drop IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'public.key_value_pairs'::regclass
          AND contype IN ('p', 'f')
    LOOP
        EXECUTE format('ALTER TABLE key_value_pairs DROP CONSTRAINT %I', constraint_to_drop.conname);
    END LOOP;

    FOR constraint_to_drop IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'public.unittests'::regclass
          AND contype = 'p'
    LOOP
        EXECUTE format('ALTER TABLE unittests DROP CONSTRAINT %I', constraint_to_drop.conname);
    END LOOP;
END $$;

ALTER TABLE key_value_pairs
    DROP COLUMN IF EXISTS test_decisionname,
    DROP COLUMN IF EXISTS "key",
    DROP COLUMN IF EXISTS value,
    DROP COLUMN IF EXISTS type;

ALTER TABLE unittests
    DROP COLUMN IF EXISTS decisionname;

ALTER TABLE unittests
    ADD CONSTRAINT pk_unittests PRIMARY KEY (id);

ALTER TABLE key_value_pairs
    ADD CONSTRAINT pk_key_value_pairs PRIMARY KEY (id),
    ADD CONSTRAINT fk_key_value_pairs_test FOREIGN KEY (test_id) REFERENCES unittests (id);

INSERT INTO domains (id, name)
VALUES (1, 'Bestuur'),
       (2, 'Sociaal domein'),
       (3, 'Fysieke leefomgeving'),
       (4, 'Publieksdiensten'),
       (5, 'Openbare order en veiligheid'),
       (6, 'Niet domeingebonden'),
       (7, 'Ondersteuning')
ON CONFLICT (id) DO NOTHING;

INSERT INTO environments (id, name)
VALUES (1, 'Ontwikkel'),
       (2, 'Productie')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('domains', 'id'),
    COALESCE((SELECT MAX(id) FROM domains), 1),
    EXISTS (SELECT 1 FROM domains)
);

SELECT setval(
    pg_get_serial_sequence('environments', 'id'),
    COALESCE((SELECT MAX(id) FROM environments), 1),
    EXISTS (SELECT 1 FROM environments)
);

SELECT setval(
    pg_get_serial_sequence('dmns', 'id'),
    COALESCE((SELECT MAX(id) FROM dmns), 1),
    EXISTS (SELECT 1 FROM dmns)
);

SELECT setval(
    pg_get_serial_sequence('change_log', 'id'),
    COALESCE((SELECT MAX(id) FROM change_log), 1),
    EXISTS (SELECT 1 FROM change_log)
);

SELECT setval(
    pg_get_serial_sequence('comments', 'id'),
    COALESCE((SELECT MAX(id) FROM comments), 1),
    EXISTS (SELECT 1 FROM comments)
);

SELECT setval(
    pg_get_serial_sequence('unittests', 'id'),
    COALESCE((SELECT MAX(id) FROM unittests), 1),
    EXISTS (SELECT 1 FROM unittests)
);

SELECT setval(
    pg_get_serial_sequence('key_value_pairs', 'id'),
    COALESCE((SELECT MAX(id) FROM key_value_pairs), 1),
    EXISTS (SELECT 1 FROM key_value_pairs)
);
